spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/democase?serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  type-aliases-package: com.xxoo.bean



